package binance

type WebSocketRequest struct {
	Method string   `json:"method"`
	Params []string `json:"params"`
	ID     int      `json:"id"`
}

type WebSocketResponse struct {
	EventType string `json:"e"`
	EventName int64  `json:"E"`
	Symbol    string `json:"s"`
	KPI       Kpi    `json:"k"`
}

type Kpi struct {
	KStartTime       int64  `json:"t"`
	KSEndTime        int64  `json:"T"`
	Symbol           string `json:"s"`
	Interval         string `json:"i"`
	FirstTradeId     int    `json:"f"`
	LastTradeId      int    `json:"L"`
	OpenPrice        string `json:"o"`
	ClosePrice       string `json:"c"`
	HighestPrice     string `json:"h"`
	LowestPrice      string `json:"l"`
	BassAssetVolume  string `json:"v"`
	NoOfTrade        int    `json:"n"`
	IsKlineClosed    bool   `json:"x"`
	QuoteAssetVolume string `json:"q"`
	Buy              string `json:"V"`
	Quote            string `json:"Q"`
	Ignore           string `json:"B"`
}

//type AutoGenerated struct {
//	EventType string `json:"e"`
//	EventTime int64  `json:"E"`
//	Symbol    string `json:"s"`
//
//	AggregateTradeID int    `json:"a"`
//	Price            string `json:"p"`
//	Quantity         string `json:"q"`
//	FirstTradeId     int    `json:"f"`
//	LastTradeId      int    `json:"l"`
//	Timestamp        int64  `json:"T"`
//	IsBuyersMarket   bool   `json:"m"`
//	IsBestPriceMatch bool   `json:"M"`
//	P                string `json:"p"`
//	P                string `json:"P"`
//	W                string `json:"w"`
//	X                string `json:"x"`
//	C                string `json:"c"`
//	Q                string `json:"Q"`
//	B                string `json:"b"`
//	B                string `json:"B"`
//	A                string `json:"a"`
//	A                string `json:"A"`
//	O                string `json:"o"`
//	H                string `json:"h"`
//	L                string `json:"l"`
//	V                string `json:"v"`
//	Q                string `json:"q"`
//	O                int64  `json:"O"`
//	C                int64  `json:"C"`
//	F                int    `json:"F"`
//	L                int    `json:"L"`
//	N                int    `json:"n"`
//}
