package binance

type WebSocketResponse struct {
	EventType        string `json:"e"`
	EventName        int64  `json:"E"`
	Symbol           string `json:"s"`
	AggregateTradeID int    `json:"a"`
	Price            string `json:"p"`
	Quantity         string `json:"q"`
	FirstTradeId     int    `json:"f"`
	LastTradeId      int    `json:"l"`
	Timestamp        int64  `json:"T"`
	IsBuyersMarket   bool   `json:"m"`
	IsBestPriceMatch bool   `json:"M"`
}

//type AutoGenerated struct {
//	EventType string `json:"e"`
//	EventTime int64  `json:"E"`
//	Symbol    string `json:"s"`
//
//	AggregateTradeID int    `json:"a"`
//	Price            string `json:"p"`
//	Quantity         string `json:"q"`
//	FirstTradeId     int    `json:"f"`
//	LastTradeId      int    `json:"l"`
//	Timestamp        int64  `json:"T"`
//	IsBuyersMarket   bool   `json:"m"`
//	IsBestPriceMatch bool   `json:"M"`
//	P                string `json:"p"`
//	P                string `json:"P"`
//	W                string `json:"w"`
//	X                string `json:"x"`
//	C                string `json:"c"`
//	Q                string `json:"Q"`
//	B                string `json:"b"`
//	B                string `json:"B"`
//	A                string `json:"a"`
//	A                string `json:"A"`
//	O                string `json:"o"`
//	H                string `json:"h"`
//	L                string `json:"l"`
//	V                string `json:"v"`
//	Q                string `json:"q"`
//	O                int64  `json:"O"`
//	C                int64  `json:"C"`
//	F                int    `json:"F"`
//	L                int    `json:"L"`
//	N                int    `json:"n"`
//}
